name: Mirror to Public Repo

on:
  push:
    branches:
      - development

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: "https://github.com/johnkayiira-jpg/training-john-mirror.git"
          pat: ${{ secrets.MIRROR_PAT }}
